baseURL = "https://pekarangan-hijau.web.app/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Pekarangan Hijau"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = true
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2 January 2006"
comments = true
readingTime = true
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = false
authorInfo = "hidup itu sementara, akhirat selamanya (namun aku percaya waulaupun hanya sementara disitu harus memberi makna)"
description="website pertanian untuk indonesia menjadi negara mandiri pangan"
previewCardImagePlacement = "bottom"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Ahmad Yusuf Maulana"
  website = "https://pekarangan-hijau.web.app/"
  email = "ahmadyusufmaulana0@gmail.com"
#   facebook = "username"
  instagram = "yuuahmad"
#   youtube = "user/username" # or channel/channelname
#   twitter = "username"
#   threads = "username"
#   linkedin = "username"
  github = "yuuahmad-aii"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5



